### ISSUE TITLE
questions 

### ISSUE THREAD

**Issue by astrocycles** [zellwk/gulp-starter-csstricks#15]
Hello,

This repo is really awesome. 
Just a few questions :
- Gulp seems to not compress the images at all, as the size is exactly the same in the dist image folder.

- when uploading on firebase I have a Warning: advanced compression encodings unavailable without ES6/C++11. Falling back to gzip. What should I add in gulp ? 

Thanks

**Comment by zellwk** [comment]
1. Gulp seems to be compressing images though. Were they already compressed before you put them into src? If so, compression may be negligible. 

2. Not sure about that, probably create a gzip step? I don't use Firebase myself.
