### ISSUE TITLE
building multiple html files and directories to /dist

### ISSUE THREAD

**Issue by alphex** [zellwk/gulp-starter-csstricks#17]
I'd like to use this for a project, but I can't get it to deliver anything besides the root index.html to /dist.
I'll eventually have something like ...

```
/index.html
/foo/index.html
/foo/subfoo1/index.html
/foo/subfoo2/index.html
/foo/subfoo2/index.html
/foo2/index.html
```
as the file directory for a super dumb static HTML website I have to build.

But your gulp file doesn't read all of that.
Can you help with a fix?

Thanks!

**Comment by zellwk** [comment]
I highly recommend something like [11ty](https://www.11ty.dev) for this. I use it myself. I might be able to work on an Eleventy tutorial in future.
