### ISSUE TITLE
useref issue?

### ISSUE THREAD

**Issue by beesman** [zellwk/gulp-starter-csstricks#3]
Great article at ccs-tricks, thank you!

I'm running into a problem when running gulp useref with the following code:

``` javascript
gulp.task('useref', function() {
  var assets = useref.assets();

  return gulp.src('app/*.html')
    .pipe(assets)
    .pipe(assets.restore())
    .pipe(useref())
    .pipe(gulp.dest('dist'));
});
```

I get the following error:
`Using gulpfile ~/Documents/project/gulpfile.js
Starting 'useref'...
'useref' errored after 224 μs
TypeError: useref.assets is not a function`

Any help/advice would be very welcome!

**Comment by zellwk** [comment]
UH yep. It's due to gulp-useref v3. https://www.npmjs.com/package/gulp-useref

Would you mind submitting a pull request? :)

**Comment by benschac** [comment]
@beesman isn't the only one having this issue!  thanks!

**Comment by benschac** [comment]
I just reverted backdown to 1.1 and everything is working for me. :)

**Comment by henrikholmlund** [comment]
Hi! I have the exact same problem. Everything works fine and dandy except useref. How do I change the version?

**Comment by zellwk** [comment]
You can do "npm install gulp-useref@version-num" to install a previous version. 

I'm currently on holiday right now, so I'll only be able to update this when I'm done. 

Stay Awesome! Zell

**Comment by henrikholmlund** [comment]
Hey! 

Thanks for the swift reply. I'll try your solution next week and see where it'll lead me. 

Best,

---

Henrik Holmlund
Tel: 070-947 18 71
henrik@henrikholmlund.se

**Comment by KrabsWong** [comment]
I didn't test the old version `v2.x` of `useref`, but I have to change the sequence about plugins for building after upgrading `useref` to `v3.x`.

**Old version**

``` javascript
// Optimizing CSS and JavaScript 
gulp.task('useref', function() {
  var assets = useref.assets();

  return gulp.src('app/*.html')
    .pipe(assets)
    // Minifies only if it's a CSS file
    .pipe(gulpIf('*.css', minifyCSS()))
    // Uglifies only if it's a Javascript file
    .pipe(gulpIf('*.js', uglify()))
    .pipe(assets.restore())
    .pipe(useref())
    .pipe(gulp.dest('dist'))
});
```

**New version**

``` javascript
// Optimizing CSS and JavaScript 
gulp.task('useref', function() {
  return gulp.src('app/*.html')
    .pipe(useref())
    // Minifies only if it's a CSS file
    .pipe(gulpIf('*.css', minifyCSS()))
    // Uglifies only if it's a Javascript file
    .pipe(gulpIf('*.js', uglify()))
    .pipe(gulp.dest('dist'))
});
```

`uglify` and `css minify` should be called after `useref`

**Comment by vikrantnegi** [comment]
I've submitted a pull request regarding this issue and once it get merged i hope the issue will be resolved.

**Comment by zellwk** [comment]
@vikrantnegi Yep I've just merged the PR. Thanks for the work! :+1:
